const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.HEIDI_BROWSER?{executablePath:process.env.HEIDI_BROWSER}:{})});try{const p=await b.newPage({viewport:{width:1440,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const url=process.env.HEIDI_URL||'http://127.0.0.1:8771/';await p.goto(url+'#kino');const ids=await p.evaluate(()=>films.map(f=>f.id));for(const id of ids){await p.locator(`.film-open[data-film="${id}"]`).click();if(['1953bbc','1974bbc','1998short'].includes(id)){assert.equal(await p.locator('#overlay [data-archive]').getAttribute('data-archive'),id);assert.equal(await p.locator('#overlay textarea').count(),0);await p.keyboard.press('Escape');continue;}assert.equal(await p.locator('#overlay [data-case]').getAttribute('data-case'),'film-'+id);assert((await p.locator('#overlay .case-question').innerText()).length>30);assert.equal(await p.locator('#overlay textarea').count(),1);await p.keyboard.press('Escape')}
await p.goto(url+'#film-1965');await p.waitForSelector('[data-case="film-1965"]');assert.equal(await p.locator('.case-figures img').count(),1);await p.locator('.case-figures img').evaluate(i=>i.decode());await p.locator('#overlay').screenshot({path:'/private/tmp/heidi-cases/revised-image-desktop.png'});await p.keyboard.press('Escape');await p.goto(url+'#film-1920');await p.waitForSelector('[data-case="film-1920"]');await p.locator('#overlay').screenshot({path:'/private/tmp/heidi-cases/film-desktop.png'});await p.locator('#draft-film-1920').fill('Peter handelt nicht aus Eifersucht.');await p.locator('[data-reflect="film-1920"]').click();assert((await p.locator('#reflection-film-1920').innerText()).includes('nicht als Zustimmung'));
await p.locator('[data-case-pair="paar-1920-1974"]').click();assert.equal(await p.locator('[data-case="paar-1920-1974"]').count(),1);await p.keyboard.press('Escape');
await p.goto(url+'#kino');await p.locator('[data-action="clear-pair"]').click();await p.locator('[data-pair="1937"]').click();await p.locator('[data-pair="2005"]').click();await p.locator('[data-action="compare"]').click();assert.equal(await p.locator('#overlay [data-reflect]').count(),0);assert.equal(await p.locator('#overlay .case-question').count(),0);await p.keyboard.press('Escape');
await p.goto(url+'#spuren');const imageIds=await p.locator('[data-trace-image]').evaluateAll(xs=>xs.map(x=>x.dataset.traceImage));for(const id of imageIds){await p.locator(`[data-trace-image="${id}"]`).click();assert.equal(await p.locator('[data-case]').getAttribute('data-case'),'bild-'+id);await p.locator(`[data-draft="bild-${id}"]`).fill('Nur zu diesem Bild: '+id)}await p.locator('[data-trace-image="1937"]').click();assert.equal(await p.locator('#draft-bild-1937').inputValue(),'Nur zu diesem Bild: 1937');await p.locator('[data-trace-image="1952"]').click();assert.equal(await p.locator('#draft-bild-1952').inputValue(),'Nur zu diesem Bild: 1952');
await p.locator('footer [data-action="workshops"]').click();assert.equal(await p.locator('#overlay [data-case-pair]').count(),9);assert.equal(await p.locator('[data-case="quelle-walther"]').count(),1);await p.keyboard.press('Escape');
await p.evaluate(()=>{state.drafts['film-1965']='Antwort zur alten Frage';state.drafts['film-1965@2']='';persist()});await p.goto(url+'#film-1965');await p.waitForSelector('#draft-film-1965');assert.equal(await p.locator('#draft-film-1965').inputValue(),'');await p.locator('#draft-film-1965').fill('Die Umarmung verbindet die Figuren.');await p.reload();assert.equal(await p.locator('#draft-film-1965').inputValue(),'Die Umarmung verbindet die Figuren.');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('heidi-cases-v3')).drafts['film-1965']),'Antwort zur alten Frage');await p.keyboard.press('Escape');
await p.setViewportSize({width:390,height:844});await p.goto(url+'#film-1920');await p.waitForSelector('[data-case="film-1920"]');assert(await p.evaluate(()=>{const d=document.querySelector('dialog');return d.scrollWidth<=d.clientWidth+1}));await p.locator('#overlay').screenshot({path:'/private/tmp/heidi-cases/film-mobile.png'});await p.keyboard.press('Escape');await p.goto(url+'#film-1965');await p.waitForSelector('.case-figures img');assert(await p.evaluate(()=>{const d=document.querySelector('dialog');return d.scrollWidth<=d.clientWidth+1}));await p.locator('#overlay').screenshot({path:'/private/tmp/heidi-cases/revised-image-mobile.png'});await p.keyboard.press('Escape');await p.goto(url+'#spuren');await p.screenshot({path:'/private/tmp/heidi-cases/image-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('Case UI PASS: 32 film tasks + 3 honest archive entries; 8 separate image drafts; 9 curated pairs; source task; unrelated pairs have no generated question; negation feedback; mobile dialog; no JS errors.')}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
