// Run with Playwright installed: HEIDI_BROWSER=/path/to/chrome NODE_PATH=/path/to/node_modules node research/exploration.browser.cjs
const assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const b=await chromium.launch({headless:true,...(process.env.HEIDI_BROWSER?{executablePath:process.env.HEIDI_BROWSER}:{})});
 const page=await b.newPage({viewport:{width:1440,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=process.env.HEIDI_URL||'http://127.0.0.1:8770/';
 await page.goto(url+'#kino');await page.waitForSelector('.film-card');assert.equal(await page.locator('.film-card').count(),35);
 assert.equal(await page.locator('iframe').count(),0);
 await page.locator('#film-search').fill('BBC');assert.equal(await page.locator('.film-card').count(),4);
 await page.locator('#film-search').fill('nichtvorhandenxxx');await page.getByText('Alle Filme wieder zeigen',{exact:true}).click();assert.equal(await page.locator('.film-card').count(),35);
 await page.locator('#video-only').check();assert.equal(await page.locator('.film-card').count(),31);await page.locator('#video-only').uncheck();
 await page.locator('[data-pair="1920"]').click();await page.locator('[data-pair="1974"]').click();await page.locator('[data-action="compare"]').click();assert.equal(await page.locator('#overlay .player-shell').count(),2);assert.equal(await page.locator('#overlay iframe').count(),0);
 await page.locator('#draft-paar-1920-1974').fill('Bei 01:20 sehe ich im Bild eine weite Landschaft. Dadurch wirkt Heidi freier, vielleicht aber auch allein.');await page.locator('[data-reflect="paar-1920-1974"]').click();assert((await page.locator('#reflection-paar-1920-1974').innerText()).includes('Vergebung'));await page.locator('[data-save="paar-1920-1974"]').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#overlay iframe').count(),0);
 await page.goto(url+'#film-1920');await page.waitForSelector('[data-seek]');await page.locator('[data-seek="63"]').click();await page.waitForFunction(()=>document.querySelector('#overlay video').currentTime>=63);await page.keyboard.press('Escape');await page.goto(url+'#film-2015');await page.waitForSelector('dialog[open]');await page.locator('[data-full="true"]').click();assert((await page.locator('#overlay video source').getAttribute('src')).includes('heidi-2015-realfilm'));await page.keyboard.press('Escape');
 await page.goto(url+'#labor');await page.waitForSelector('#montage-strip');await page.locator('[data-move="buch"][data-delta="-1"]').click();assert.equal(await page.locator('[data-segment]').nth(1).getAttribute('data-segment'),'buch');
 await page.locator('#segment-duration').fill('2');await page.locator('#montage-mute').check();await page.locator('[data-action="play-montage"]').click();await page.waitForFunction(()=>document.querySelector('#montage-player').currentTime>0,{timeout:15000});await page.waitForFunction(()=>document.querySelector('#montage-label').textContent.includes('zu Ende'),{timeout:20000});
 await page.locator('#draft-montage').fill('Die Buchseite folgt auf die Alp. Dadurch wirkt die Stadt wie eine Erinnerung.');await page.locator('[data-save="montage"]').click();await page.screenshot({path:'/private/tmp/heidi-redesign/labor.png'});
 await page.goto(url+'#spuren');await page.locator('#trace-canvas>img').click({position:{x:100,y:120}});await page.locator('#draft-bild-buch-alp').fill('Die Hände liegen nah beieinander. Ich vermute Fürsorge.');await page.locator('[data-save="bild-buch-alp"]').click();assert.equal(await page.locator('.pin:not(.pending)').count(),1);await page.reload();assert.equal(await page.locator('.pin:not(.pending)').count(),1);await page.screenshot({path:'/private/tmp/heidi-redesign/spuren.png'});
 await page.locator('[data-action="notebook"]').click();assert.equal(await page.locator('.note').count(),3);assert.equal(await page.locator('.note-question').count(),3);
 const download=page.waitForEvent('download');await page.locator('[data-action="export"]').click();assert.equal((await download).suggestedFilename(),'Heidi_Meine_Entdeckungen.txt');await page.locator('[data-restore]').click();await page.waitForSelector('#montage-strip');assert.equal(await page.locator('[data-segment]').nth(1).getAttribute('data-segment'),'buch');
 await page.goto(url+'#zeit');await page.locator('[data-era="7"]').click();assert.equal(await page.locator('#time-year').innerText(),'2023');await page.locator('[data-era-compare="7"]').click();assert.equal(await page.locator('#overlay .player-shell').count(),2);await page.keyboard.press('Escape');
 await page.locator('footer [data-action="sources"]').click();assert((await page.locator('#overlay-body').innerText()).includes('bereitgestellten Dokumente'));await page.keyboard.press('Escape');
 for(const width of [390,768,1024]){await page.setViewportSize({width,height:844});for(const route of ['start','kino','labor','spuren','zeit']){await page.goto(url+'#'+route);await page.waitForTimeout(150);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${width} ${route}`);if(width===390)await page.screenshot({path:'/private/tmp/heidi-redesign/mobile-'+route+'.png',fullPage:true})}}
 assert.deepEqual(errors,[]);console.log('Browser PASS: 35 films, search/filter, two-film comparison, full film, actual 4-clip playback, montage restore, image pins, persistence, feedback, export, timeline, source library; no JS errors or overflow at 390/768/1024px.');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
